//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesReturnDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblApprovalMatrix
    {
        public int Matrix_Id { get; set; }
        public string Country { get; set; }
        public string BUType { get; set; }
        public string Division { get; set; }
        public int RequestType { get; set; }
        public Nullable<decimal> SRV_Value { get; set; }
        public Nullable<decimal> InvoiceAge { get; set; }
        public string ComplaintHandler { get; set; }
        public string ComplaintManager { get; set; }
        public string LogisticsManager { get; set; }
        public string LogisticsHead { get; set; }
        public Nullable<decimal> SegmentHeadHRV { get; set; }
        public Nullable<decimal> SegmentInvoiceAge { get; set; }
        public string VP { get; set; }
        public string President { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
