//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesReturnDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBarCodeDetail
    {
        public long BarCode_ID { get; set; }
        public string SKU_Name { get; set; }
        public string SKU_Code { get; set; }
        public string SKU_Desc { get; set; }
        public string Batch_No { get; set; }
        public Nullable<System.DateTime> Manufacturing_Date { get; set; }
        public string Shelf_Life { get; set; }
        public string Unit { get; set; }
        public string Pack_Size { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Carton { get; set; }
        public string UniqueId { get; set; }
    }
}
