//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesReturnDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployeeMaster
    {
        public int Id { get; set; }
        public string DepotName { get; set; }
        public string CommercialCode { get; set; }
        public string Depotcode { get; set; }
        public string CSO { get; set; }
        public string ComplaintHandler { get; set; }
        public string ComplaintManager { get; set; }
        public string LogisticsHead { get; set; }
        public string ISC { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string CommercialHead { get; set; }
    }
}
