//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesReturnDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFlowMatrix
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public int RequestType { get; set; }
        public string Options { get; set; }
        public Nullable<long> ComplaintHandler { get; set; }
        public Nullable<long> ComplaintManager { get; set; }
        public Nullable<long> LogisticsHead { get; set; }
        public Nullable<long> ISC { get; set; }
        public Nullable<long> RH { get; set; }
        public Nullable<long> SegmentHead { get; set; }
        public Nullable<long> VP { get; set; }
        public Nullable<long> President { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
