//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesReturnDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRequestHeader
    {
        public long RequestHeaderId { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<long> DepotId { get; set; }
        public Nullable<long> DealerId { get; set; }
        public Nullable<int> ReasonForReturn { get; set; }
        public string SKUCode { get; set; }
        public string SKUName { get; set; }
        public string BatchNo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string RequestTypeOption { get; set; }
        public string EPNo { get; set; }
        public Nullable<int> ParentRequest { get; set; }
        public Nullable<bool> IsCommercialSettlement { get; set; }
        public Nullable<bool> MaterialWillGoToDealer { get; set; }
        public string ReasonForCommercialSettlement { get; set; }
        public string DetailsForMaterialGoToDealer { get; set; }
        public string DocketNumber { get; set; }
        public Nullable<System.DateTime> DocketDate { get; set; }
    }
}
