//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesReturnDAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblApproverDetail
    {
        public long ApproverDetails_Id { get; set; }
        public int Approver_Id { get; set; }
        public int Role_Id { get; set; }
        public int Status_Id { get; set; }
        public string Remark { get; set; }
        public string AssignedTo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
